replicaCount: 6

image:
  repository: ghcr.io/daviddland/devsecops-task-mvp
  tag: "6639b48511e95399a5f6eddfed007d8217ef9951"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8000

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"