replicaCount: 6

image:
  repository: ghcr.io/daviddland/devsecops-task-mvp
  tag: "696298797b9f1526d8b505c7fc443cd0a4a72238"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8000

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"